# Generated by extendr: Do not edit by hand

# nolint start

#
# This file was created with the following call:
#   .Call("wrap__make_extera_wrappers", use_symbols = TRUE, package_name = "extera")

#' @usage NULL
#' @useDynLib extera, .registration = TRUE
NULL

RustExTera <- new.env(parent = emptyenv())

RustExTera$default <- function() .Call(wrap__RustExTera__default)

RustExTera$new <- function(dir) .Call(wrap__RustExTera__new, dir)

RustExTera$add_string_templates <- function(templates) .Call(wrap__RustExTera__add_string_templates, self, templates)

RustExTera$add_file_templates <- function(templates) .Call(wrap__RustExTera__add_file_templates, self, templates)

RustExTera$list_templates <- function() .Call(wrap__RustExTera__list_templates, self)

RustExTera$render_to_file <- function(template_name, context_string, outfile) .Call(wrap__RustExTera__render_to_file, self, template_name, context_string, outfile)

RustExTera$render_to_string <- function(template_name, context_string) .Call(wrap__RustExTera__render_to_string, self, template_name, context_string)

RustExTera$autoescape_on <- function() .Call(wrap__RustExTera__autoescape_on, self)

RustExTera$autoescape_off <- function() .Call(wrap__RustExTera__autoescape_off, self)

#' @export
`$.RustExTera` <- function (self, name) { func <- RustExTera[[name]]; environment(func) <- environment(); func }

#' @export
`[[.RustExTera` <- `$.RustExTera`


# nolint end
